import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: {
          base: "var(--bg-base)",
          subtle: "var(--bg-subtle)",
          sunken: "var(--bg-sunken)",
          elevated: "var(--bg-elevated)",
          overlay: "var(--bg-overlay)",
        },
        surface: {
          DEFAULT: "var(--surface)",
          hover: "var(--surface-hover)",
          pressed: "var(--surface-pressed)",
          selected: "var(--surface-selected)",
          disabled: "var(--surface-disabled)",
        },
        border: {
          DEFAULT: "var(--border)",
          subtle: "var(--border-subtle)",
          strong: "var(--border-strong)",
          focus: "var(--border-focus)",
          divider: "var(--border-divider)",
        },
        text: {
          DEFAULT: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          disabled: "var(--text-disabled)",
          inverse: "var(--text-inverse)",
          link: "var(--text-link)",
          linkHover: "var(--text-link-hover)",
          onBrand: "var(--text-on-brand)",
        },
        royal: {
          DEFAULT: "var(--royal)",
          hover: "var(--royal-hover)",
          active: "var(--royal-active)",
          subtle: "var(--royal-subtle)",
          subtleHover: "var(--royal-subtle-hover)",
          fg: "var(--royal-fg)",
        },
        gold: {
          DEFAULT: "var(--gold)",
          hover: "var(--gold-hover)",
          active: "var(--gold-active)",
          subtle: "var(--gold-subtle)",
          subtleHover: "var(--gold-subtle-hover)",
          fg: "var(--gold-fg)",
        },
        success: { DEFAULT: "var(--success)", bg: "var(--success-bg)", border: "var(--success-border)", fg: "var(--success-fg)" },
        warning: { DEFAULT: "var(--warning)", bg: "var(--warning-bg)", border: "var(--warning-border)", fg: "var(--warning-fg)" },
        danger:  { DEFAULT: "var(--danger)",  bg: "var(--danger-bg)",  border: "var(--danger-border)",  fg: "var(--danger-fg)" },
        info:    { DEFAULT: "var(--info)",    bg: "var(--info-bg)",    border: "var(--info-border)",    fg: "var(--info-fg)" },
        bet: {
          win: "var(--bet-win)",
          lose: "var(--bet-lose)",
          draw: "var(--bet-draw)",
          pool: "var(--bet-pool)",
          stake: "var(--bet-stake)",
          jackpot: "var(--bet-jackpot)",
          streak: "var(--bet-streak)",
          hot: "var(--bet-hot)",
          cold: "var(--bet-cold)",
        },
      },
      fontFamily: {
        display: ["var(--font-display)", "Sora", "Inter", "system-ui", "Helvetica Neue", "Arial", "sans-serif"],
        sans:    ["var(--font-sans)", "Inter", "system-ui", "Helvetica Neue", "Arial", "Noto Sans", "sans-serif"],
        mono:    ["var(--font-mono)", "JetBrains Mono", "SF Mono", "Menlo", "Consolas", "monospace"],
      },
      fontSize: {
        micro:      ["10px", { lineHeight: "14px", letterSpacing: "0.4px" }],
        caption:    ["11px", { lineHeight: "15px", letterSpacing: "0.2px" }],
        label:      ["12px", { lineHeight: "16px", letterSpacing: "0.05px" }],
        "body-sm":  ["13px", { lineHeight: "18px", letterSpacing: "-0.05px" }],
        body:       ["14px", { lineHeight: "20px", letterSpacing: "-0.08px" }],
        "body-lg":  ["16px", { lineHeight: "24px", letterSpacing: "-0.16px" }],
        "title-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.36px" }],
        "title-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.55px" }],
        "title-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.85px" }],
        "display-3":["36px", { lineHeight: "40px", letterSpacing: "-1.2px" }],
        "display-2":["48px", { lineHeight: "52px", letterSpacing: "-1.7px" }],
        "display-1":["64px", { lineHeight: "68px", letterSpacing: "-2.4px" }],
      },
      spacing: {
        "0.5": "2px",
        "1": "4px",
        "1.5": "8px",
        "2": "12px",
        "3": "16px",
        "4": "20px",
        "5": "24px",
        "6": "32px",
        "7": "40px",
        "8": "48px",
        "9": "64px",
        "10": "80px",
        "11": "96px",
        "12": "128px",
      },
      borderRadius: {
        xs: "2px",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        pill: "999px",
      },
      boxShadow: {
        e0: "none",
        e1: "var(--shadow-1)",
        e2: "var(--shadow-2)",
        e3: "var(--shadow-3)",
        e4: "var(--shadow-4)",
        e5: "var(--shadow-5)",
        "glow-gold": "var(--glow-gold)",
        "glow-blue": "var(--glow-blue)",
        "glow-win": "var(--glow-win)",
        "glow-jackpot": "var(--glow-jackpot)",
      },
      backgroundImage: {
        "g-brand": "var(--g-brand)",
        "g-gold": "var(--g-gold)",
        "g-jackpot": "var(--g-jackpot)",
        "g-aurora": "var(--g-aurora)",
        "g-pool": "var(--g-pool)",
      },
      transitionTimingFunction: {
        standard: "cubic-bezier(0.2, 0, 0, 1)",
        decelerate: "cubic-bezier(0, 0, 0.2, 1)",
        accelerate: "cubic-bezier(0.4, 0, 1, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      transitionDuration: {
        micro: "80ms",
        short: "160ms",
        medium: "240ms",
        long: "420ms",
        celebration: "1200ms",
      },
      zIndex: {
        base: "0",
        raised: "10",
        dropdown: "1000",
        sticky: "1100",
        drawer: "1200",
        modal: "1300",
        popover: "1400",
        toast: "1500",
        tooltip: "1600",
        celebration: "1700",
      },
      screens: {
        xs: "360px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
    },
  },
  plugins: [],
};

export default config;
