const fs = require("fs");
const f = "scripts/simple-journey-flag.test.mts";
let s = fs.readFileSync(f, "utf8");
const rep = (from, to) => { if (s.split(from).length !== 2) throw new Error("not once: " + from.slice(0, 80)); s = s.replace(from, to); };
rep(`  // a request the resolver does not show the journey to is served what it was served before. Each journey arm is a LAZY\r\n  // binding in its own Suspense, since WP6c a \`next/dynamic\` part of the shell's one client module, \`shell-lazy.tsx\`\r\n  // (AppShell's own \`React.lazy\` split nothing: VODACOM-PLAN §0h point 20), so the journey chrome's code stays out of\r\n  // the first-load bundle every classic visitor downloads. The header's fallback is the bar's own empty box (its\r\n  // height, panel and border), so a journey page does not jump while that code arrives; the tabs need none, because\r\n  // the rail takes no room in the page. And nothing else renders or loads the journey chrome, or loads it into a\r\n  // classic layout component.`,
`  // a request the resolver does not show the journey to is served what it was served before. Each journey arm is a LAZY\r\n  // binding, since WP6c a \`next/dynamic\` part of the shell's one client module, \`shell-lazy.tsx\` (AppShell's own\r\n  // \`React.lazy\` split nothing: VODACOM-PLAN §0h point 20), so the journey chrome's code stays out of the first-load\r\n  // bundle every classic visitor downloads. ⭐ AND THE ARM IS THE PART ITSELF, IN NO SUSPENSE BOUNDARY (R4-J,\r\n  // 2026-10-09; E36): in one, React 19.2 drew the boundary's fallback (the bar's empty box; nothing for the rail) in the\r\n  // page's first HTML and moved the part in after the shell by an inline script — an empty header band and no rail on\r\n  // every Slow 3G mid-load tile. And nothing else renders or loads the journey chrome, or loads it into a classic\r\n  // layout component.`);
rep(`  const SWAP_HEADER = '{journeyShown ? <Suspense fallback={<div aria-hidden="true" className="kp-jhdr" />}><LazyJourneyTopBar user={topUser} onBreak={promoSuppressed} proposalsState={proposalsState} inviteVisible={inviteVisible} invitePaid={invitePaid} /></Suspense> : <TopAppBar user={topUser} proposalsState={proposalsState} inviteVisible={inviteVisible} invitePaid={invitePaid} />}';`,
`  const SWAP_HEADER = "{journeyShown ? <LazyJourneyTopBar user={topUser} onBreak={promoSuppressed} proposalsState={proposalsState} inviteVisible={inviteVisible} invitePaid={invitePaid} /> : <TopAppBar user={topUser} proposalsState={proposalsState} inviteVisible={inviteVisible} invitePaid={invitePaid} />}";`);
rep(`  const SWAP_RAIL = "{journeyShown ? <Suspense fallback={null}><LazyJourneyTabs userId={session?.userId ?? null} /></Suspense> : <BottomNav isAuthed={!!session} proposalsState={proposalsState} inviteVisible={inviteVisible} walletHeld={!!topUser.walletHeld} />}";`,
`  const SWAP_RAIL = "{journeyShown ? <LazyJourneyTabs userId={session?.userId ?? null} /> : <BottomNav isAuthed={!!session} proposalsState={proposalsState} inviteVisible={inviteVisible} walletHeld={!!topUser.walletHeld} />}";`);
rep(`  ok("10.shell.chrome.header · the journey header renders only in the journeyShown arm, lazily, over the bar's own empty box, and the else arm is today's TopAppBar with today's props",\r\n    tally(SWAP_HEADER) === 1 && tally("<LazyJourneyTopBar") === 1 && tally("<TopAppBar") === 1,\r\n    j({ swap: tally(SWAP_HEADER), journey: tally("<LazyJourneyTopBar"), classic: tally("<TopAppBar") }));`,
`  ok("10.shell.chrome.header · the journey header renders only in the journeyShown arm, lazily and in no Suspense boundary (no empty box in front of it), and the else arm is today's TopAppBar with today's props",\r\n    tally(SWAP_HEADER) === 1 && tally("<LazyJourneyTopBar") === 1 && tally("<TopAppBar") === 1 && tally('className="kp-jhdr"') === 0,\r\n    j({ swap: tally(SWAP_HEADER), journey: tally("<LazyJourneyTopBar"), classic: tally("<TopAppBar"), box: tally('className="kp-jhdr"') }));`);
rep(`  ok("10.shell.chrome.tabs · the journey tabs render only in the journeyShown arm, lazily, and the else arm is today's BottomNav with today's props",`,
`  ok("10.shell.chrome.tabs · the journey tabs render only in the journeyShown arm, lazily and in no Suspense boundary, and the else arm is today's BottomNav with today's props",`);
rep(`    world: (w) => ({ ...w, shell: w.shell.replace("{journeyShown ? <Suspense fallback={null}><LazyJourneyTabs", "{true ? <Suspense fallback={null}><LazyJourneyTabs") }) },`,
`    world: (w) => ({ ...w, shell: w.shell.replace("{journeyShown ? <LazyJourneyTabs", "{true ? <LazyJourneyTabs") }) },`);
rep(`  { name: "the journey header's fallback leaves no box, so a journey page jumps while its code arrives (S6 WP6b)", expect: new RegExp("^10[.]shell[.]chrome[.]header"),\r\n    world: (w) => ({ ...w, shell: w.shell.replace('<Suspense fallback={<div aria-hidden="true" className="kp-jhdr" />}><LazyJourneyTopBar', "<Suspense fallback={null}><LazyJourneyTopBar") }) },`,
`  { name: "the journey header back in a Suspense boundary over the bar's empty box, so a slow first paint shows an empty band (R4-J, E36)", expect: new RegExp("^10[.]shell[.]chrome[.]header"),\r\n    world: (w) => ({ ...w, shell: w.shell.replace("{journeyShown ? <LazyJourneyTopBar user={topUser}", '{journeyShown ? <Suspense fallback={<div aria-hidden="true" className="kp-jhdr" />}><LazyJourneyTopBar user={topUser}').replace("invitePaid={invitePaid} /> : <TopAppBar", "invitePaid={invitePaid} /></Suspense> : <TopAppBar") }) },\r\n  { name: "the journey tabs back in a Suspense boundary, so a slow first paint has no rail (R4-J, E36)", expect: new RegExp("^10[.]shell[.]chrome[.]tabs"),\r\n    world: (w) => ({ ...w, shell: w.shell.replace("{journeyShown ? <LazyJourneyTabs userId={session?.userId ?? null} /> :", "{journeyShown ? <Suspense fallback={null}><LazyJourneyTabs userId={session?.userId ?? null} /></Suspense> :") }) },`);
fs.writeFileSync(f, s, "utf8");
console.log("ok");
