/**
 * Admin CONTROL gates — does the page offer exactly what the action will accept?
 *
 *   npx tsx scripts/control-gates.test.mts      (npm run test:control-gates)
 *
 * WHY THIS EXISTS — findings E-18 and E-19, live QA campaign 2026-08-01, both
 * evidenced on production.
 *
 * The admin console gates in three layers (nav item → route → action) and
 * `admin-nav-groups.ts:134` states they "MUST agree with the route + action gates
 * (same domains)". Twice, they did not:
 *
 *   E-18  `/admin/resolver-queue` is the `trading` domain, so a MODERATOR reaches the
 *         page and every control on it — but "Re-check this market now" and the
 *         two-admin toggle require `compliance`. Under DEFAULT_GRANTS those sets are
 *         DISJOINT, so on production only the 9 ADMIN accounts could work the queue.
 *   E-19  `<AiToolkit>` renders in the SHELL HEADER — every admin page, every console
 *         role — and all four of its switches require `compliance` too.
 *
 * The symptom that makes this more than a UX wart: clicking a control the UI offered
 * writes `privilege_escalation_blocked` at **SECURITY** severity, so an ordinary
 * operator's legitimate click lands in the compliance officer's log as an attempted
 * privilege escalation. Production has exactly such a row, generated by the QA trading
 * officer clicking the real button:
 *
 *   2026-07-31 23:11:58Z · SECURITY · privilege_escalation_blocked
 *   actor usr_429885ab43c0cb4ce134dd7e · target recheckMarketNow
 *   {"role":"MODERATOR","domain":"compliance"}
 *
 * WHAT IS ASSERTED. §1–§2 drive the REAL `canUseControl` against the REAL grant matrix
 * — E-4 established that a gate which is missing is precisely what reads as present in
 * review, so the behaviour is exercised, not grepped. §3–§4 are drift detectors on the
 * wiring, because the defect is a DISAGREEMENT between two files and no single file
 * looks wrong on its own. §5 is the general catcher: it fails on the NEXT surface that
 * grows a control whose domain its page cannot see.
 *
 * ⛔ Note what is deliberately NOT asserted: that MODERATOR *should* be able to
 * re-check a market. It should not — these are compliance decisions and AI-spend
 * controls, and `roles.ts` says CONFIG_ROLES/COMPLIANCE_ROLES are "NEVER MODERATOR".
 * Widening the grants would "fix" the bug by deleting the control. The invariant is
 * agreement, not access.
 */
import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { CONTROL_DOMAIN, canUseControl, type ControlId } from "../src/lib/server/control-gates.ts";
import { __resetGrantsForTest } from "../src/lib/server/rbac.ts";
import { ADMIN_DOMAINS, domainForPath, type Role } from "../src/lib/server/roles.ts";

const ROOT = process.cwd();
let pass = 0, fail = 0;
const ok = (label: string, cond: boolean, extra = "") => {
  cond ? pass++ : fail++;
  console.log(`${cond ? "PASS" : "FAIL"} ${label}${extra ? ` — ${extra}` : ""}`);
};
const read = (rel: string) => readFileSync(join(ROOT, rel), "utf8");

// The grant table is the DB's when there is one; with no DATABASE_URL the in-memory
// store is authoritative. Reset it so every assertion below is against DEFAULT_GRANTS,
// the seed matrix that is what production actually runs (verified live: RoleDomainGrant
// holds no override rows for MODERATOR or COMPLIANCE).
__resetGrantsForTest();

// ── 1 · The model ────────────────────────────────────────────────────────────
{
  const ids = Object.keys(CONTROL_DOMAIN) as ControlId[];
  ok("1 · at least one control is declared", ids.length > 0, `${ids.length} declared`);

  const bad = ids.filter((id) => !(ADMIN_DOMAINS as readonly string[]).includes(CONTROL_DOMAIN[id]));
  ok("1 · every declared domain is a real AdminDomain", bad.length === 0, bad.join(", "));

  // The id is the action name minus `Action`, so the enforcement point is mechanically
  // findable. A cute alias breaks §3's ability to locate it.
  const odd = ids.filter((id) => !/^[a-z][A-Za-z0-9]*$/.test(id));
  ok("1 · ids are lowerCamel action names", odd.length === 0, odd.join(", "));
}

// ── 2 · BEHAVIOUR: the real canUseControl, every role × every control ────────
// This is the half that actually reproduces E-18. The expected matrix is written out
// in full rather than derived from DEFAULT_GRANTS — deriving it from the same source
// the implementation reads would make the test agree with any bug it contains.
{
  const EXPECT: Record<string, Partial<Record<ControlId, boolean>>> = {
    // Owner bypasses the grant table entirely and can never be locked out.
    ADMIN:      { recheckMarketNow: true,  setTwoAdminAuth: true,  resolveMarket: true,  aiToolkit: true,  emergencyVoidMarket: true,  voidUpDownRound: true },
    // ⭐ E-18 in one line: trading yes, compliance no. Sees the queue, cannot re-check;
    //    sees the markets table, cannot work its kill switch.
    // ⚠️ `voidUpDownRound: true` is a DELIBERATE, EVIDENCED decision, not a default —
    //    see the block on it in control-gates.ts. It shipped as `compliance` first and
    //    production proved that unusable: /admin/updown/rounds is a `trading` route, so
    //    a compliance officer could not even open the page, and the remedy ended up
    //    Owner-only. Flipping this line back to `false` is how you re-break E-23.
    MODERATOR:  { recheckMarketNow: false, setTwoAdminAuth: false, resolveMarket: true,  aiToolkit: false, emergencyVoidMarket: false, voidUpDownRound: true },
    // ⭐ The other half: can act, cannot even reach the trading page that hosts it.
    //    …and that is exactly why `voidUpDownRound` is FALSE here: a control a role can
    //    work but never reach is not a control. The round explorer stays trading-owned.
    COMPLIANCE: { recheckMarketNow: true,  setTwoAdminAuth: true,  resolveMarket: false, aiToolkit: true,  emergencyVoidMarket: true,  voidUpDownRound: false },
    FINANCE:    { recheckMarketNow: false, setTwoAdminAuth: false, resolveMarket: false, aiToolkit: false, emergencyVoidMarket: false, voidUpDownRound: false },
    GROWTH:     { recheckMarketNow: false, setTwoAdminAuth: false, resolveMarket: false, aiToolkit: false, emergencyVoidMarket: false, voidUpDownRound: false },
    SUPPORT:    { recheckMarketNow: false, setTwoAdminAuth: false, resolveMarket: false, aiToolkit: false, emergencyVoidMarket: false, voidUpDownRound: false },
    // Read-only everywhere, including the domains it can view.
    AUDITOR:    { recheckMarketNow: false, setTwoAdminAuth: false, resolveMarket: false, aiToolkit: false, emergencyVoidMarket: false, voidUpDownRound: false },
    PLAYER:     { recheckMarketNow: false, setTwoAdminAuth: false, resolveMarket: false, aiToolkit: false, emergencyVoidMarket: false, voidUpDownRound: false },
    AGENT:      { recheckMarketNow: false, setTwoAdminAuth: false, resolveMarket: false, aiToolkit: false, emergencyVoidMarket: false, voidUpDownRound: false },
  };

  // ⛔ NOT vacuous by omission. `Partial<Record<…>>` lets a new control be added and
  // silently go untested for every role — which is how a gate reads as covered and is
  // not. Every control must appear in every row.
  {
    const ids = Object.keys(CONTROL_DOMAIN) as ControlId[];
    const gaps = Object.entries(EXPECT).flatMap(([role, row]) =>
      ids.filter((id) => !(id in row)).map((id) => `${role}.${id}`));
    ok("2 · every control is asserted for every role (no silent gaps)", gaps.length === 0, gaps.join(", "));
  }

  for (const [role, row] of Object.entries(EXPECT)) {
    for (const [id, want] of Object.entries(row) as [ControlId, boolean][]) {
      const got = await canUseControl(role as Role, id);
      ok(`2 · ${role} · ${id} → ${want}`, got === want, got === want ? "" : `got ${got}`);
    }
  }

  // An unauthenticated render must never offer a privileged control.
  for (const id of Object.keys(CONTROL_DOMAIN) as ControlId[]) {
    ok(`2 · no session · ${id} → false`, (await canUseControl(null, id)) === false);
  }
  ok("2 · empty-string role → false", (await canUseControl("", "recheckMarketNow")) === false);
  ok("2 · unknown role → false", (await canUseControl("WIZARD", "recheckMarketNow")) === false);
}

// ── 3 · The ACTION half: each control's enforcement reads CONTROL_DOMAIN ──────
// If an action hard-codes its domain, the page has nothing to read and the two can
// drift silently — which is exactly how E-18 and E-19 happened.
{
  const SITES: Record<ControlId, string> = {
    recheckMarketNow: "src/app/admin/resolver-queue/resolution-mode-action.ts",
    setTwoAdminAuth: "src/app/admin/resolver-queue/resolution-policy-action.ts",
    resolveMarket: "src/app/markets/actions.ts",
    aiToolkit: "src/app/admin/_actions/ai-toolkit.ts",
    emergencyVoidMarket: "src/app/markets/actions.ts",
  };
  for (const [id, file] of Object.entries(SITES) as [ControlId, string][]) {
    ok(`3 · ${id} · enforcement site exists`, existsSync(join(ROOT, file)), file);
    const src = existsSync(join(ROOT, file)) ? read(file) : "";
    ok(`3 · ${id} · action reads CONTROL_DOMAIN.${id}`,
       src.includes(`CONTROL_DOMAIN.${id}`), file);
    // …and does not ALSO carry a stale literal that a reader would believe instead.
    const literals = [...src.matchAll(/canAct\([^,]+,\s*"([a-z]+)"\)/g)].map((m) => m[1]);
    ok(`3 · ${id} · no hard-coded domain literal left behind`,
       literals.length === 0, literals.join(", "));
  }
}

// ── 4 · The PAGE half: every gated control is rendered behind its own flag ────
// Source-level by necessity (these are RSC + client components), but paired with §2's
// behavioural drive: together they say "the flag is computed correctly AND it is the
// thing the JSX branches on".
{
  const queue = read("src/app/admin/resolver-queue/page.tsx");
  ok("4 · resolver-queue asks canUseControl", queue.includes("canUseControl("));
  for (const id of ["recheckMarketNow", "setTwoAdminAuth", "resolveMarket"] as ControlId[]) {
    ok(`4 · resolver-queue computes ${id}`, queue.includes(`"${id}"`));
  }
  // Each of the three controls must appear ONLY inside a conditional, with a
  // ControlLocked alternative. A bare <RecheckButton /> is the pre-fix state.
  for (const [tag, flag] of [
    ["RecheckButton", "canRecheck"],
    ["TwoAdminToggle", "canSetPolicy"],
    ["ResolveControls", "canResolve"],
  ] as const) {
    const uses = [...queue.matchAll(new RegExp(`<${tag}\\b`, "g"))].length;
    ok(`4 · <${tag}> is rendered exactly once`, uses === 1, `${uses} uses`);
    ok(`4 · <${tag}> sits behind ${flag}`,
       new RegExp(`${flag}\\s*\\?[\\s\\S]{0,400}<${tag}\\b`).test(queue));
  }
  ok("4 · resolver-queue offers a ControlLocked fallback", queue.includes("<ControlLocked"));

  // The markets curation table — third instance, and the highest-stakes control of the
  // three: emergency void refunds every open stake on a LIVE market.
  const markets = read("src/app/admin/markets/page.tsx");
  ok("4 · markets asks canUseControl(emergencyVoidMarket)",
     markets.includes("canUseControl(") && markets.includes('"emergencyVoidMarket"'));
  ok("4 · <EmergencyVoidControl> sits behind canEmergencyVoid",
     /canEmergencyVoid\s*\?[\s\S]{0,300}<EmergencyVoidControl\b/.test(markets));

  // The ceremony page is the same class — it is `trading` VIEW but sealing is
  // `trading` ACT, which the Owner can split live at /admin/roles.
  const ceremony = read("src/app/admin/resolver/[id]/page.tsx");
  ok("4 · ceremony asks canUseControl(resolveMarket)",
     ceremony.includes('canUseControl(') && ceremony.includes('"resolveMarket"'));
  ok("4 · ceremony gates <ResolutionCeremony> on canResolve",
     /canResolve\s*\?[\s\S]{0,300}<ResolutionCeremony\b/.test(ceremony));

  // E-19: the shell must pass the flag; a default-true prop with no call site is the
  // bug wearing a fix's clothes.
  const shell = read("src/components/admin/admin-shell.tsx");
  ok("4 · shell passes canAct to <AiToolkit>",
     /<AiToolkit[\s\S]{0,300}canAct=\{await canUseControl\(/.test(shell));
  const toolkit = read("src/components/admin/ai-toolkit.tsx");
  ok("4 · AiToolkit honours canAct (read-only rows)", toolkit.includes("readOnly={!canAct}"));
  ok("4 · AiToolkit renders a state, not a disabled Toggle, when read-only",
     /readOnly\s*\?[\s\S]{0,600}<Toggle/.test(toolkit));
}

// ── 5 · DRIFT DETECTOR: the next surface that grows a mis-gated control ──────
// Every file that refuses with `privilege_escalation_blocked` and names its domain as
// a LITERAL must be one whose route domain matches that literal. If it does not match
// — or if the file has no route at all, so no page can infer it — the control has to
// be declared in CONTROL_DOMAIN, which is what gives the page something to read.
//
// Adversarially checked while writing: reverting ai-toolkit.ts to its hard-coded
// "compliance" makes this section FAIL by filename, which is exactly how E-19 should
// have been caught.
{
  function walk(dir: string): string[] {
    const out: string[] = [];
    const abs = join(ROOT, dir);
    if (!existsSync(abs)) return out;
    for (const name of readdirSync(abs)) {
      const rel = join(dir, name);
      if (statSync(join(ROOT, rel)).isDirectory()) out.push(...walk(rel));
      else if (/\.tsx?$/.test(name)) out.push(rel.replace(/\\/g, "/"));
    }
    return out;
  }

  /** `src/app/admin/resolver-queue/x-action.ts` → `/admin/resolver-queue`. Route groups
   *  `(x)`, private `_dirs` and dynamic `[id]` segments are not part of the URL.
   *
   *  Returns null — "cannot infer, must declare" — for anything outside `src/app/admin`.
   *  That is not pedantry: the THIRD instance of E-18 was `emergencyVoidMarketAction`,
   *  which lives in the PLAYER tree (`src/app/markets/actions.ts`) while its control
   *  renders on the admin markets page. Co-location is not evidence of where a control
   *  appears, so an un-inferable file has to say which domain it demands. */
  function routeOf(file: string): string | null {
    const d = dirname(file).replace(/\\/g, "/"); // e.g. src/app/admin/resolver/[id]
    if (!d.startsWith("src/app/admin")) return null;
    const segs = d.slice("src/app/".length).split("/");
    if (segs.some((s) => s.startsWith("_"))) return null; // _actions — renders anywhere
    return "/" + segs.filter((s) => !/^\(.*\)$/.test(s) && !/^\[.*\]$/.test(s)).join("/");
  }

  // The shared guard takes its domain as a parameter — it is the definition, not a
  // drift site.
  const EXEMPT = new Set(["src/lib/server/rbac-guard.ts"]);

  const offenders: string[] = [];
  let scanned = 0;
  for (const file of [...walk("src/app"), ...walk("src/lib/server")]) {
    if (EXEMPT.has(file)) continue;
    const src = read(file);
    if (!src.includes("privilege_escalation_blocked")) continue;
    const literals = [...src.matchAll(/canAct\([^,]+,\s*"([a-z]+)"\)/g)].map((m) => m[1]);
    if (literals.length === 0) continue; // uses CONTROL_DOMAIN, requireStaff, or a tier
    scanned++;
    const declares = src.includes("CONTROL_DOMAIN");
    const route = routeOf(file);
    for (const lit of new Set(literals)) {
      if (route === null) {
        // No route ⇒ the control can render anywhere (shell header, shared service),
        // so nothing can infer its domain. It MUST be declared.
        if (!declares) offenders.push(`${file}: gates on "${lit}" but has no route to infer it from, and does not declare a control`);
      } else if (domainForPath(route) !== lit && !declares) {
        offenders.push(`${file}: route ${route} is "${domainForPath(route)}" but the action demands "${lit}" — declare it in CONTROL_DOMAIN so the page can hide the control`);
      }
    }
  }
  ok("5 · no admin action gates on a domain its own page cannot see",
     offenders.length === 0, offenders.join(" | "));
  ok("5 · the detector actually scanned files (not vacuous)", scanned > 0, `${scanned} literal-gated files`);
}

console.log(`\n${fail === 0 ? "ALL PASS" : "FAILURES"} — ${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
