/**
 * THE ASSET PLAYBOOK — guard.
 *
 * Runs the pure engine in `src/lib/updown-playbook.ts` over a fixture of REAL measurements:
 * 19 assets, 1-minute bars pulled from TwelveData 2026-08-10 (`fixtures-updown-profiles.json`).
 * Every expectation below is a number that was measured, not a number that was chosen — so this
 * suite fails both when the engine breaks and when the world changes underneath it, and the
 * second is a finding, not a flake.
 *
 * ⛔ The fixture is deliberately NOT regenerated by this test. A guard that refreshes its own
 * corpus proves only that the code agrees with itself today.
 *
 * Run: npx tsx scripts/updown-playbook.test.mts   ·   RED proof: scripts/updown-playbook-red.mjs
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  DEFAULT_POLICY, resolvePolicy, buildPlaybook, judgeAsset, judgeChoice,
  deriveMinDuration, deriveDeadHours, deadWindowLabel, profileUsable,
  type AssetProfile, type PlaybookPolicy,
} from "../src/lib/updown-playbook.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const RAW = JSON.parse(readFileSync(join(HERE, "fixtures-updown-profiles.json"), "utf8")) as Record<string, AssetProfile>;
const ALLOWED = [3, 5, 10, 15, 30, 60];
const NOW = Date.parse("2026-08-10T12:00:00.000Z");
const P = DEFAULT_POLICY;

let pass = 0, fail = 0;
const ok = (label: string, cond: boolean, extra?: string) => {
  if (cond) { pass++; } else { fail++; console.log(`  FAIL ${label}${extra ? ` — ${extra}` : ""}`); }
};
const book = (sym: string, policy: PlaybookPolicy = P, catalogueMin: number | null = null) =>
  buildPlaybook(sym, RAW[sym], policy, ALLOWED, catalogueMin, NOW);

// ── 1. Policy: defaults, overrides, and the clamps that stop a bad row breaking the console ──
{
  ok("1.1 defaults are frozen", Object.isFrozen(DEFAULT_POLICY));
  ok("1.2 empty override yields defaults", resolvePolicy(undefined).maxFloorShareOfMove === P.maxFloorShareOfMove);
  ok("1.3 junk override yields defaults", resolvePolicy("nonsense").blockRefundRate === P.blockRefundRate);
  ok("1.4 a valid key overrides", resolvePolicy({ maxFloorShareOfMove: 0.2 }).maxFloorShareOfMove === 0.2);
  ok("1.5 an out-of-range value is ignored, not applied",
     resolvePolicy({ maxFloorShareOfMove: 99 }).maxFloorShareOfMove === P.maxFloorShareOfMove);
  ok("1.6 a non-numeric value is ignored", resolvePolicy({ blockRefundRate: "high" }).blockRefundRate === P.blockRefundRate);
  ok("1.7 unknown keys do not leak in", !("nope" in resolvePolicy({ nope: 1 })));
  const clamped = resolvePolicy({ warnRefundRate: 0.9, blockRefundRate: 0.2 });
  ok("1.8 warn above block is clamped to block, never left inverted",
     clamped.warnRefundRate === clamped.blockRefundRate, `warn=${clamped.warnRefundRate}`);
  const c2 = resolvePolicy({ warnDirectionalEdge: 0.4, maxDirectionalEdge: 0.06 });
  ok("1.9 the same clamp applies to the directional pair", c2.warnDirectionalEdge === c2.maxDirectionalEdge);
  ok("1.10 booleans override", resolvePolicy({ allowOverrideOnWarn: false }).allowOverrideOnWarn === false);
}

// ── 2. ESCALATE-ONLY. The rule updown-symbols.ts §316 states, applied to this source too. ────
{
  const measured = deriveMinDuration(RAW["BTC/USD"], P, ALLOWED, null, NOW).minutes;
  ok("2.1 Bitcoin's measured minimum is a real duration", measured != null && ALLOWED.includes(measured), String(measured));
  const withFloor = deriveMinDuration(RAW["BTC/USD"], P, ALLOWED, 30, NOW).minutes;
  ok("2.2 a STRICTER catalogue floor wins over measurement", withFloor === 30, String(withFloor));
  const looser = deriveMinDuration(RAW["XAU/USD"], P, ALLOWED, 3, NOW).minutes;
  ok("2.3 a LOOSER catalogue floor never lowers the measured one", looser != null && looser > 3, String(looser));
  ok("2.4 no profile + no catalogue floor = no opinion, not a green light",
     deriveMinDuration(undefined, P, ALLOWED, null, NOW).minutes === null);
  ok("2.5 no profile still honours the catalogue floor",
     deriveMinDuration(undefined, P, ALLOWED, 15, NOW).minutes === 15);
}

// ── 3. The measured minimums, per asset. These are the study's numbers. ─────────────────────
{
  const gold = book("XAU/USD");
  ok("3.1 gold's minimum derives to 30 minutes", gold.minDurationMinutes === 30, String(gold.minDurationMinutes));
  ok("3.2 gold blocks every length below it",
     [3, 5, 10, 15].every((d) => gold.blockedDurations.includes(d)), gold.blockedDurations.join(","));
  ok("3.3 gold's reason quotes a measured number", /Measured over \d+ days/.test(gold.minDurationWhy ?? ""));

  const btc = book("BTC/USD");
  ok("3.4 Bitcoin recommends 5 minutes", btc.recommendedDurations.includes(5), btc.recommendedDurations.join(","));
  ok("3.5 Bitcoin does NOT recommend 3 minutes", !btc.recommendedDurations.includes(3));
  ok("3.6 …but does not refuse it either — margin cannot fix a flat window, length can",
     !btc.blockedDurations.includes(3), btc.blockedDurations.join(","));
  ok("3.7 Bitcoin recommends 15 and 60", btc.recommendedDurations.includes(15) && btc.recommendedDurations.includes(60));

  const eth = book("ETH/USD");
  ok("3.8 Ethereum recommends 5 minutes, like Bitcoin", eth.recommendedDurations.includes(5), eth.recommendedDurations.join(","));

  const ltc = book("LTC/USD");
  ok("3.9 Litecoin recommends nothing at all", ltc.recommendedDurations.length === 0, ltc.recommendedDurations.join(","));
  ok("3.10 …and blocks its short lengths outright", ltc.blockedDurations.includes(3) && ltc.blockedDurations.includes(5));
}

// ── 4. The asset-level axes — the two questions a refund rate cannot answer. ────────────────
{
  ok("4.1 Bitcoin passes as a fair market", judgeAsset(RAW["BTC/USD"], P, NOW).level === 1,
     judgeAsset(RAW["BTC/USD"], P, NOW).reason);
  const tzs = judgeAsset(RAW["USD/TZS"], P, NOW);
  ok("4.2 USD/TZS is REFUSED — a 0% refund rate hid a pegged, exploitable tape", tzs.level === 3, tzs.reason);
  ok("4.3 …and that refusal cannot be overridden", tzs.overridable === false);
  ok("4.4 USD/TZS would look PERFECT on refund rate alone — the point of the extra axis",
     (RAW["USD/TZS"]!.refundRate[5] ?? 1) < 0.01, String(RAW["USD/TZS"]!.refundRate[5]));
  ok("4.5 EUR/USD is refused on its directional edge", judgeAsset(RAW["EUR/USD"], P, NOW).level === 3);
  ok("4.6 gold is NOT refused — its variance ratio drifts but no naive strategy beats the fee",
     judgeAsset(RAW["XAU/USD"], P, NOW).level < 3, judgeAsset(RAW["XAU/USD"], P, NOW).reason);
  ok("4.7 …it is a level 2, and it says why", judgeAsset(RAW["XAU/USD"], P, NOW).level === 2);
  const thin = judgeAsset(RAW["XLM/USD"], P, NOW);
  ok("4.8 XLM's 96.4% coverage refuses it before any other test runs", thin.level === 3 && /coverage|minutes asked for/i.test(thin.reason), thin.reason);
  ok("4.9 an unmeasured asset is a caveat, never a pass", judgeAsset(undefined, P, NOW).level === 2);
  ok("4.10 the directional test is symmetric — a 43% edge is as bad as a 57% one", (() => {
    const mk = (v: number): AssetProfile => ({ ...RAW["BTC/USD"]!, persistence: { 5: v } });
    const lo = judgeAsset(mk(0.42), P, NOW), hi = judgeAsset(mk(0.58), P, NOW);
    return lo.level === 3 && hi.level === 3;
  })());
}

// ── 5. Dead windows — the finding market-calendar.ts does not model. ────────────────────────
{
  const goldHours = deriveDeadHours(RAW["XAU/USD"], P, NOW);
  ok("5.1 gold's dead window is found", goldHours.includes(21), goldHours.join(",") || "none");
  ok("5.2 …and it is ONLY that hour", goldHours.length === 1, goldHours.join(","));
  ok("5.3 Bitcoin has no dead window — the control that proves it is the market, not the feed",
     deriveDeadHours(RAW["BTC/USD"], P, NOW).length === 0);
  ok("5.4 the label reads in EAT, not UTC", deadWindowLabel(book("XAU/USD"), 180) === "00:00–01:00",
     String(deadWindowLabel(book("XAU/USD"), 180)));
  ok("5.5 no dead window yields no label", deadWindowLabel(book("BTC/USD"), 180) === null);
  ok("5.6 a stricter ratio finds more hours, a looser one fewer", (() => {
    const strict = deriveDeadHours(RAW["XAU/USD"], { ...P, deadWindowRatio: 0.6 }, NOW).length;
    const loose = deriveDeadHours(RAW["XAU/USD"], { ...P, deadWindowRatio: 0.01 }, NOW).length;
    return strict >= 1 && loose === 0;
  })());
}

// ── 6. Freshness is asymmetric: it gates optimism, never caution. ───────────────────────────
{
  const stale: AssetProfile = { ...RAW["XAU/USD"]!, measuredAt: "2026-01-01T00:00:00.000Z" };
  ok("6.1 a stale profile is not usable", profileUsable(stale, P, NOW) === false);
  ok("6.2 a short profile is not usable", profileUsable({ ...RAW["BTC/USD"]!, days: 2 }, P, NOW) === false);
  const staleBook = buildPlaybook("XAU/USD", stale, P, ALLOWED, 15, NOW);
  ok("6.3 a stale profile still honours the catalogue floor — its blocks stand",
     staleBook.minDurationMinutes === 15, String(staleBook.minDurationMinutes));
  ok("6.4 a stale profile CANNOT clear anything — nothing is recommended off it",
     staleBook.recommendedDurations.length === 0, staleBook.recommendedDurations.join(","));
  ok("6.5 and it says so in plain words", /days old|only \d+ days/.test(staleBook.profileNote), staleBook.profileNote);
}

// ── 7. judgeChoice — the verdict a form field and a server action both read. ────────────────
{
  const gold = book("XAU/USD");
  const below = judgeChoice(gold, RAW["XAU/USD"], P, 5);
  ok("7.1 below the minimum is a refusal", below.level === 3);
  ok("7.2 …and it is NOT overridable, whatever the policy says about warnings",
     judgeChoice(gold, RAW["XAU/USD"], { ...P, allowOverrideOnWarn: true }, 5).overridable === false);
  const at = judgeChoice(gold, RAW["XAU/USD"], P, 30);
  ok("7.3 at the minimum it is allowed", at.level <= 2, at.reason);
  const btc3 = judgeChoice(book("BTC/USD"), RAW["BTC/USD"], P, 3);
  ok("7.4 Bitcoin at 3 minutes warns and is overridable", btc3.level === 2 && btc3.overridable === true, btc3.reason);
  ok("7.5 …and the warning carries the actual percentage", /\d+\.\d%/.test(btc3.reason), btc3.reason);
  ok("7.6 turning overrides off makes the same warning final",
     judgeChoice(book("BTC/USD"), RAW["BTC/USD"], { ...P, allowOverrideOnWarn: false }, 3).overridable === false);
  ok("7.7 an unmeasured length is a caveat, not a pass", (() => {
    const v = judgeChoice(book("BTC/USD"), { ...RAW["BTC/USD"]!, refundRate: {} }, P, 15);
    return v.level === 2 && /Nobody has measured/.test(v.reason);
  })());
}

// ── 8. Nothing is hardcoded: moving a knob must move the answer. ────────────────────────────
{
  const loose = { ...P, maxFloorShareOfMove: 0.35 };
  const g1 = book("XAU/USD").minDurationMinutes;
  const g2 = book("XAU/USD", loose).minDurationMinutes;
  ok("8.1 loosening the floor share lowers gold's minimum", g2 != null && g1 != null && g2 < g1, `${g1} → ${g2}`);
  const tight = { ...P, blockRefundRate: 0.01, warnRefundRate: 0.005 };
  ok("8.2 tightening the refund limits shrinks what is recommended",
     book("BTC/USD", tight).recommendedDurations.length < book("BTC/USD").recommendedDurations.length);
  ok("8.3 a permissive directional limit stops refusing USD/TZS",
     judgeAsset(RAW["USD/TZS"], { ...P, maxDirectionalEdge: 0.4 }, NOW).level < 3);
  // ⚠️ Deliberately asserts the REASON moved on, not that the verdict flipped. Relaxing coverage
  // clears XLM's first refusal and it is immediately refused again on its directional edge — a
  // second, independent gate. Asserting `level < 3` here would have been asserting that one
  // permissive knob unlocks an asset, which is exactly what a defence in depth must not do.
  {
    const strictReason = judgeAsset(RAW["XLM/USD"], P, NOW).reason;
    const looseVerdict = judgeAsset(RAW["XLM/USD"], { ...P, minCoverage: 0.9 }, NOW);
    ok("8.4 relaxing coverage clears THAT refusal", !/minutes asked for/.test(looseVerdict.reason), looseVerdict.reason);
    ok("8.5 …but XLM is still refused, by the next gate down", looseVerdict.level === 3, looseVerdict.reason);
    ok("8.6 …and the two refusals give different reasons", strictReason !== looseVerdict.reason);
  }
}

// ── 9. The whole catalogue, swept. Printed so a reviewer sees the shape, not just a count. ──
{
  console.log("\n  ── every measured asset, as the engine sees it ──");
  console.log(`  ${"asset".padEnd(10)}${"verdict".padEnd(9)}${"min".padStart(5)}  ${"recommended".padEnd(16)}dead(UTC)  why`);
  let listable = 0;
  for (const sym of Object.keys(RAW).sort()) {
    const b = book(sym);
    const a = judgeAsset(RAW[sym], P, NOW);
    const tag = a.level === 3 ? "REFUSED" : a.level === 2 ? "caution" : "clean";
    if (a.level < 3 && b.recommendedDurations.length) listable++;
    console.log(
      `  ${sym.padEnd(10)}${tag.padEnd(9)}${String(b.minDurationMinutes ?? "-").padStart(5)}  ` +
      `${(b.recommendedDurations.join(",") || "—").padEnd(16)}${(b.deadHoursUtc.join(",") || "—").padEnd(11)}` +
      a.reason.slice(0, 62),
    );
  }
  ok("9.1 at least three assets survive every gate", listable >= 3, `listable=${listable}`);
  ok("9.2 Bitcoin is one of them", book("BTC/USD").recommendedDurations.length > 0);
  ok("9.3 the engine refuses more than it accepts on this universe — an honest screen", (() => {
    const refused = Object.keys(RAW).filter((s) => judgeAsset(RAW[s], P, NOW).level === 3).length;
    return refused >= Object.keys(RAW).length / 3;
  })());
}

// ── 10. THE WIRING. The engine being right is not the same as it being CONNECTED, and every
//        section above tests only the maths. These test the three seams it now sits in.
{
  const { symbolReadiness, findSymbol } = await import("../src/lib/server/updown-symbols.ts");
  const { toReadinessAdvice } = await import("../src/lib/server/updown-playbook-store.ts");
  const { marketSessionAt, isMarketOpenAt } = await import("../src/lib/server/market-calendar.ts");

  // 10a · symbolReadiness now takes a fifth source, and takes the STRICTEST of all of them.
  const btc = findSymbol("BTC/USD");
  ok("10.1 with no playbook verdict, readiness is unchanged", symbolReadiness(btc, 5).level <= 2);
  ok("10.2 a playbook ③ refuses the pairing outright",
     symbolReadiness(btc, 5, undefined, undefined, { level: 3, message: "unfit" }).level === 3);
  ok("10.3 …and the operator is told the playbook's own sentence",
     symbolReadiness(btc, 5, undefined, undefined, { level: 3, message: "unfit" }).reason === "unfit");
  ok("10.4 a playbook ② becomes a caveat, not a refusal",
     symbolReadiness(btc, 5, undefined, undefined, { level: 2, message: "thin" }).level === 2);
  ok("10.5 …and the caveat survives alongside others rather than winning a race",
     symbolReadiness(btc, 5, undefined, undefined, { level: 2, message: "thin" }).reason.includes("thin"));
  ok("10.6 a playbook ① adds no noise", symbolReadiness(btc, 5, undefined, undefined, { level: 1, message: "" }).level === 1);

  // 10b · the adapter, which exists so a `.reason` never reaches the catalogue as a `.message`.
  ok("10.7 the adapter renames reason → message", toReadinessAdvice({ level: 2, reason: "x", overridable: true })?.message === "x");
  ok("10.8 …and passes undefined through as undefined", toReadinessAdvice(undefined) === undefined);

  // 10c · the calendar. ⚠️ 2026-08-12 is a WEDNESDAY, chosen so the weekend rules cannot mask
  //       the daily break — a Saturday would be shut for the bigger reason and prove nothing.
  const wed21 = "2026-08-12T21:30:00.000Z", wed14 = "2026-08-12T14:30:00.000Z";
  ok("10.9 without dead hours the calendar behaves exactly as before", marketSessionAt("macro", wed21).open === true);
  const broke = marketSessionAt("macro", wed21, [21]);
  ok("10.10 a dead hour closes the session", broke.open === false);
  ok("10.11 …with the session-break reason the type has always declared and never emitted",
     broke.open === false && broke.reason === "session-break", broke.open === false ? broke.reason : "open");
  ok("10.12 …and names the window in the detail", broke.open === false && /21:00–22:00 UTC/.test(broke.detail));
  ok("10.13 an hour outside the break stays open", marketSessionAt("macro", wed14, [21]).open === true);
  ok("10.14 crypto ignores dead hours entirely — it has no session to break",
     marketSessionAt("crypto", wed21, [21]).open === true);
  ok("10.15 the weekend still wins over the break, so the operator hears the bigger reason", (() => {
    const sat = marketSessionAt("macro", "2026-08-15T21:30:00.000Z", [21]);
    return sat.open === false && sat.reason === "weekend";
  })());
  ok("10.16 the boolean helper threads the hours too", isMarketOpenAt("macro", wed21, [21]) === false);
}

// ── 11. THE OPS SCRIPT'S ENTRY POINT — the bug that printed nothing and exited 0. ───────────
{
  const { readFileSync } = await import("node:fs");
  const src = readFileSync(join(HERE, "ops-updown-profile.mts"), "utf8");
  ok("11.1 run-if-main compares URLs, never a hand-glued file:// string",
     /pathToFileURL\(process\.argv\[1\]/.test(src));
  ok("11.2 …and the broken form is gone",
     !/import\.meta\.url === `file:\/\/\$\{process\.argv\[1\]\}`/.test(src));
  // ⛔ The property, not the spelling: on a Windows-shaped path the two must still agree.
  const { pathToFileURL } = await import("node:url");
  const win = "F:\\kipindi-main\\scripts\\ops-updown-profile.mts";
  ok("11.3 the glued form genuinely fails on a Windows path (why this test exists)",
     `file://${win}` !== pathToFileURL(win).href);
  ok("11.4 the ops script is registered so test:orphans can see it",
     JSON.parse(readFileSync(join(HERE, "..", "package.json"), "utf8")).scripts["ops:updown-profile"] != null);
}

console.log(`\n${fail === 0 ? "PASS" : "FAIL"}  updown-playbook — ${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
