/**
 * Anchors for `red:house-bot-money` — each puts back one money defect the seam exists to prevent, on the
 * file where it would live. DATA, so `test:red-anchors` can audit that every `from` still resolves exactly
 * once without running the harness.
 *
 * `suite` names what the harness runs for a mutation: `money-mem` / `caps-mem` (the case file on the
 * memory store — fast), `money-pg` / `caps-pg` (the full suite on a scratch Postgres — slow, used only for
 * what memory cannot show: SQL and lock timeouts), `seam` (`test:house-bot-seam`). `expect` is the text of
 * the assertion that must turn red — any other red is WRONG-ASSERTION.
 *
 * ⛔ A red anchor quotes SOURCE. Editing one of these lines must be paired with re-anchoring here.
 */
const SVC = "src/lib/server/market-service.ts";
const SEAM = "src/lib/server/house-bot/seam.ts";
const DAL = "src/lib/server/house-bot-dal.ts";

export const MUTATIONS = [
  // ── N1 (04 N1 Tests, red:house-bot-money) ─────────────────────────────────────────────────────────
  {
    name: "N1-1 · Enter now THIN sizes against the raw opposite pool instead of lockedForHouse",
    file: SEAM,
    from: `      const lockedOpp = pool![opposite(side)].locked;`,
    to: `      const lockedOpp = rawPool(opposite(side));`,
    expect: "5.17 · Enter now THIN against NO money placed under 7 s ago",
    suite: "caps-mem",
  },
  {
    name: "N1-2 · the entry condition is re-chosen from the market's state instead of read from the claimed row",
    file: SEAM,
    from: `    if (intent.entryCondition === "OPENER") {`,
    to: `    if (fresh.yesPool === 0 && fresh.noPool === 0) {`,
    expect: "5.18 · an Enter now THIN row on an empty poll",
    suite: "caps-mem",
  },
  {
    name: "N1-3 / N2-M2 · the staff-chosen count covers MANUAL rows only (memory twin)",
    file: DAL,
    from: `const isStaffChosen = (i: Pick<StoredHouseBotIntent, "kind" | "targetId">): boolean => i.kind === "MANUAL" || i.targetId != null;`,
    to: `const isStaffChosen = (i: Pick<StoredHouseBotIntent, "kind" | "targetId">): boolean => i.kind === "MANUAL";`,
    expect: "1.21 · one Enter now + one targeted reaction placed",
    suite: "caps-mem",
  },
  {
    name: "N1-3b · the H2 staff-chosen gate forgets targeted reactions",
    file: SEAM,
    from: `  if (intent.kind === "MANUAL" || intent.targetId != null) {\n    const staff = await houseBotIntentStore.staffChosenPlacedToday({ houseBotId: ctx.botId }, tx);`,
    to: `  if (intent.kind === "MANUAL") {\n    const staff = await houseBotIntentStore.staffChosenPlacedToday({ houseBotId: ctx.botId }, tx);`,
    expect: "1.21 · one Enter now + one targeted reaction placed",
    suite: "caps-mem",
  },
  {
    name: "N1-4 · H0 treats a non-CLAIMED intent as a key mismatch",
    file: SEAM,
    from: `  const intent = await houseBotIntentStore.get(ctx.intentId);\n  if (!intent ||`,
    to: `  const loaded = await houseBotIntentStore.get(ctx.intentId);\n  const intent = loaded && loaded.status === "CLAIMED" ? loaded : null;\n  if (!intent ||`,
    expect: "2.1 · a cancelled intent reaches markPlaced and ends house_intent_superseded",
    suite: "money-mem",
  },
  {
    name: "N1-5 · the seam's staleAt re-read is removed",
    file: SEAM,
    from: `  if (freshness && freshness.status === "CLAIMED" && !freshness.fresh) {`,
    to: `  if (false) {`,
    expect: "2.4 · a CLAIMED intent past staleAt ends house_intent_stale",
    suite: "money-mem",
  },
  {
    name: "N1-6 · lockedForHouse stops excluding non-PLAYER accounts (memory twin)",
    file: DAL,
    from: `      const eligible = !!u && u.role === "PLAYER" && !liveHolders.has(u.id)`,
    to: `      const eligible = !!u && !liveHolders.has(u.id)`,
    expect: "4.3 · locked NO money held only by an AGENT counts 0",
    suite: "money-mem",
  },
  {
    name: "N1-6pg · lockedForHouse's SQL stops excluding non-PLAYER accounts",
    file: DAL,
    from: "      + ` (u.\"role\"::text = 'PLAYER'`",
    to: "      + ` (true`",
    expect: "4.3 · locked NO money held only by an AGENT counts 0",
    suite: "money-pg",
  },
  {
    name: "N1-7 · LOCK_MARGIN_MS = 0",
    file: "src/lib/house-bot/constants.ts",
    from: `export const LOCK_MARGIN_MS = MAX_TOLERATED_SKEW_MS + CLAIM_SKEW_GUARD_MS;`,
    to: `export const LOCK_MARGIN_MS = 0;`,
    expect: "4.1 · NO money placed under LOCK_MARGIN_MS ago does not count",
    suite: "money-mem",
  },
  {
    name: "N1-8 · a rate cap (MIN_GAP) is checked before the staff-chosen caps",
    file: SEAM,
    from: `  // H2_ORDER:staff\n`,
    to: `  if (bot.freqMinGapSec == null || (usage.lastPlacedAt != null && Date.now() - Date.parse(usage.lastPlacedAt) < bot.freqMinGapSec * 1000)) return capReached("MIN_GAP");\n  // H2_ORDER:staff\n`,
    expect: "2.3 · STAFF_CHOSEN_PER_DAY + MIN_GAP → STAFF_CHOSEN_PER_DAY",
    suite: "caps-mem",
  },
  // ── N2 ────────────────────────────────────────────────────────────────────────────────────────────
  {
    name: "N2-M1 · TARGET_ONCE removed from H2",
    file: SEAM,
    from: `    if (intent.targetId != null && intent.decision.reactTo === "FIRST"`,
    to: `    if (false && intent.targetId != null && intent.decision.reactTo === "FIRST"`,
    expect: "1.20 · a second reaction of the same FIRST target → TARGET_ONCE",
    suite: "caps-mem",
  },
  {
    name: "N2-M3 · a targeted COUNTER sizes against the raw opposite pool",
    file: SEAM,
    from: `    const against = intent.targetId != null ? pool![opposite(side)].locked : pool![opposite(side)].lockedA15;`,
    to: `    const against = intent.targetId != null ? rawPool(opposite(side)) : pool![opposite(side)].lockedA15;`,
    expect: "5.19 · a targeted COUNTER whose trigger is still inside its margin",
    suite: "caps-mem",
  },
  // ── PLAN §3 core ──────────────────────────────────────────────────────────────────────────────────
  {
    name: "H4 · markPlaced finding no CLAIMED row no longer aborts the money writes",
    file: SVC,
    from: `            if (!placed) throw new BetAbort("HOUSE_SUPERSEDED");`,
    to: `            void placed;`,
    expect: "2.1 · a cancelled intent reaches markPlaced and ends house_intent_superseded",
    suite: "money-mem",
  },
  {
    name: "H4 · the control row is not re-read inside house:control",
    file: SEAM,
    from: `  if (!control.enabled) return refuse({ ok: false, error: "House bots are off.", code: "SUSPENDED", reason: "house_disabled" });`,
    to: `  void control.enabled;`,
    expect: "4.6 · a bet already past H1, waiting on house:control, meets an OFF written meanwhile",
    suite: "caps-mem",
  },
  {
    name: "H5 · the position loses its house marker",
    file: SVC,
    from: `      // SEAM:marker\n      ...(ctx.kind === "house" ? { houseBotId: ctx.botId } : {}),`,
    to: `      // SEAM:marker\n      ...(ctx.kind === "house" ? {} : {}),`,
    expect: "1.2 · the position carries the house marker",
    suite: "money-mem",
  },
  {
    name: "H5 · the BET_PLACED transaction loses its house marker",
    file: SVC,
    from: `            // SEAM:txnMarker\n            ...(ctx.kind === "house" ? { houseBotId: ctx.botId } : {}),`,
    to: `            // SEAM:txnMarker\n            ...(ctx.kind === "house" ? {} : {}),`,
    expect: "1.4 · the BET_PLACED transaction carries the same marker",
    suite: "money-mem",
  },
  {
    name: "(e) · cashOutPosition lets the holder sell a house stake",
    file: SVC,
    from: `    // SEAM:cashOutPosition\n    if (p.houseBotId != null) {`,
    to: `    // SEAM:cashOutPosition\n    if (false) {`,
    expect: "1.13 · …and the position stays OPEN",
    suite: "money-mem",
  },
  {
    name: "(b) · the replay goes back to returning another account's bet",
    file: SVC,
    from: `        if (existing.userId !== userId || (ctx.kind === "house" ? existing.houseBotId !== ctx.botId : existing.houseBotId != null)) {`,
    to: `        if (false) {`,
    expect: "6.1 · player C reusing player A's key → idempotency_key_conflict",
    suite: "money-mem",
  },
  {
    name: "(j) · the in-lock replay stops saying replayed",
    file: SVC,
    from: `            replayed: true as const,`,
    to: ``,
    expect: "6.3 · CONTROL · A's own retry still replays, now marked replayed: true (j)",
    suite: "money-mem",
  },
  {
    name: "I3 · a second bot may join a market another bot holds",
    file: SEAM,
    from: `  if (market.otherBotOpen) return refuse(conflict("OTHER_BOT"));`,
    to: `  void market.otherBotOpen;`,
    expect: "3.8 · bot B on the same market → house_market_conflict{OTHER_BOT}",
    suite: "money-mem",
  },
  {
    name: "N1 §3 · the blackout ignores a reopened market",
    file: "src/lib/server/house-bot/blackout.ts",
    from: `  return { blocked: stamped || freshClaim || row.reopenedAt != null };`,
    to: `  return { blocked: stamped || freshClaim };`,
    expect: "5.3 · a poll closed on a result and reopened by an officer",
    suite: "caps-mem",
  },
  {
    name: "A9 · the house bet's lock_timeout is removed",
    file: SVC,
    from: "    if (ctx.kind === \"house\" && lockTx) await lockTx.$executeRawUnsafe(`SET LOCAL lock_timeout = '${HOUSE_BET_LOCK_TIMEOUT}'`);",
    to: "    void HOUSE_BET_LOCK_TIMEOUT;",
    expect: "6.1 · house:control held → the house bet returns BUSY after the 2 s lock_timeout",
    suite: "caps-pg",
  },

  // ── The 3-lens review of commit 2 (wf_0ba267ab-81f): each finding's fix, put back ────────────────────
  {
    name: "MC-1 · H2 stops re-reading the bot's status inside the wallet lock",
    file: SEAM,
    from: `  if (!bot || bot.status !== "ACTIVE" || bot.userId !== userId) return`,
    to: `  if (!bot || bot.userId !== userId) return`,
    expect: "2.5 · a bot paused under its wallet lock while a claimed bet waits",
    suite: "caps-mem",
  },
  {
    name: "LIE-01 · Enter now OPENER ignores a share limit that is NOT SET",
    file: SEAM,
    from: `      if (control.gStaffChosenMaxCounterpartyShare == null) return concentration();\n`,
    to: ``,
    expect: "5.8b · share limit NOT SET → an Enter now OPENER on an empty poll is refused",
    suite: "caps-mem",
  },
  {
    name: "LIE-02 · the automated OPENER stops requiring both pools empty",
    file: SEAM,
    from: `  } else if (intent.kind === "OPENER") {\n    if (fresh.yesPool !== 0 || fresh.noPool !== 0) return refuse(conditionGone("OPENER"));`,
    to: `  } else if (intent.kind === "OPENER") {\n    if (false as boolean) return refuse(conditionGone("OPENER"));`,
    expect: "4.5 · OPENER on a poll holding a player's stake",
    suite: "money-mem",
  },
  {
    name: "LIE-02 · Enter now OPENER stops requiring both pools empty",
    file: SEAM,
    from: `    if (intent.entryCondition === "OPENER") {\n      if (fresh.yesPool !== 0 || fresh.noPool !== 0) return refuse(conditionGone("OPENER"));`,
    to: `    if (intent.entryCondition === "OPENER") {\n      if (false as boolean) return refuse(conditionGone("OPENER"));`,
    expect: "4.5 · Enter now OPENER on a poll holding a player's stake",
    suite: "money-mem",
  },
  {
    name: "LIE-02 · a COUNTER whose trigger is no longer OPEN still bets",
    file: SEAM,
    from: `    if (!trigger || trigger.status !== "OPEN") {`,
    to: `    if (!trigger) {`,
    expect: "4.6 · a COUNTER whose trigger was sold back",
    suite: "money-mem",
  },
  {
    name: "LIE-02 · TRIGGER_BOTH_SIDES removed",
    file: SEAM,
    from: `    if (theirs.some((p) => p.status === "OPEN" && p.side === side)) return refuse(conflict("TRIGGER_BOTH_SIDES"));\n`,
    to: ``,
    expect: "4.7 · the trigger account also holds the house's side",
    suite: "money-mem",
  },
  {
    name: "LIE-02 · OPPOSITE_SIDE removed",
    file: SEAM,
    from: `  if (open.some((p) => p.houseBotId != null && p.side !== input.side)) return conflict("OPPOSITE_SIDE");\n`,
    to: ``,
    expect: "4.8a · the same bot then NO on that market",
    suite: "money-mem",
  },
  {
    name: "LIE-03 · the round lock forgets opensAt + durationMinutes and waits for the market's close",
    file: SEAM,
    from: `    const lockAt = round ? Math.min(Date.parse(round.opensAt) + round.durationMinutes * 60_000, closesAt) : Number.NaN;`,
    to: `    const lockAt = round ? closesAt : Number.NaN;`,
    expect: "5.13b · a real round whose opensAt + durationMinutes has passed",
    suite: "caps-mem",
  },
  {
    name: "LIE-04 · the market-closed check skipped for players on the 4th line under SEAM:lockTimeout",
    file: SVC,
    from: `      if (!fresh || fresh.status !== "LIVE" || isSelectionClosed(fresh) || Date.parse(fresh.resolutionAt) <= Date.now()) {`,
    to: `      if (ctx.kind === "player" && (!fresh || fresh.status !== "LIVE" || isSelectionClosed(fresh) || Date.parse(fresh.resolutionAt) <= Date.now())) {`,
    expect: "4.1 · every ctx.kind comparison in market-service.ts sits under a SEAM: marker",
    suite: "seam",
  },
  {
    name: "LIE-05 · objection standing refused when SOME position is house-marked (every → some)",
    file: "src/lib/server/objections-service.ts",
    from: `  if (minePositions.every((p) => p.houseBotId != null)) return { eligible: false, why: "HOUSE_STAKE_ONLY" };`,
    to: `  if (minePositions.some((p) => p.houseBotId != null)) return { eligible: false, why: "HOUSE_STAKE_ONLY" };`,
    expect: "6.n4 · a holder with a liquidity stake AND their own stake is eligible",
    suite: "seam",
  },
  {
    name: "GATE-1 · the comment chip counts house-marked positions again",
    file: "src/lib/comment-side.ts",
    from: `p.status === "OPEN" && p.houseBotId == null);`,
    to: `p.status === "OPEN");`,
    expect: "6.m1 · a liquidity stake never gives its holder a side chip",
    suite: "seam",
  },
  {
    name: "MC-3 · the orphan refund loses its house marker",
    file: SVC,
    from: `// SEAM:markerOrphan — the house marker travels to every txn of a marked position (PLAN §3 propagation).\n      ...(p.houseBotId ? { houseBotId: p.houseBotId } : {}),\n`,
    to: `// SEAM:markerOrphan — the house marker travels to every txn of a marked position (PLAN §3 propagation).\n`,
    expect: "10.1 · the orphaned house stake is refunded once, and its refund carries the house marker",
    suite: "money-mem",
  },
  {
    name: "UX-1 · a house-only holder is invited to object again",
    file: SVC,
    from: `      houseOnly: everyPosition.filter((p) => p.userId === userId).every((p) => p.houseBotId != null),`,
    to: `      houseOnly: false,`,
    expect: "8.10 · the house-only holder's verdict notice has NO objection invitation",
    suite: "money-mem",
  },
  {
    name: "UX-1 · houseOnly computed as 'has any house stake' (a mixed holder loses the invitation)",
    file: SVC,
    from: `      houseOnly: everyPosition.filter((p) => p.userId === userId).every((p) => p.houseBotId != null),`,
    to: `      houseOnly: everyPosition.some((p) => p.userId === userId && p.houseBotId != null),`,
    expect: "8.11 · the mixed holder keeps the invitation",
    suite: "money-mem",
  },
  // ── D19c · the un-build (C4 rulings 143–149): each mutation puts one removed disclosure BACK, and a case must go red. ──
  {
    name: "D19-1 · a holder's WIN notice names the house stake again",
    file: SVC,
    from: "m.titleZh ? `${m.titleZh} · ${p.id}` : null), positionPermalinkHref(p.id));",
    to: "m.titleZh ? `${m.titleZh} · ${p.id}` : null), positionPermalinkHref(p.id) + (p.houseBotId != null ? \"#50pick-liquidity-stake\" : \"\"));",
    expect: "8.2 · …and its English body is the plain template",
    suite: "money-mem",
  },
  {
    name: "D19-2 · selection closed splits the holder's figures again (the personal notice excludes house positions)",
    file: SVC,
    from: "    const mine = open.filter((p) => p.userId === userId);\n    const ifYes",
    to: "    const mine = open.filter((p) => p.userId === userId && p.houseBotId == null);\n    if (mine.length === 0) continue;\n    const ifYes",
    expect: "8.6 · selection closed → exactly ONE notice for the holder, naming BOTH figures",
    suite: "money-mem",
  },
  {
    name: "D19-3 · the cash-out refusal names the liquidity stake again",
    file: SVC,
    from: "    if (p.houseBotId != null) {\n      return { ok: false as const, error: \"The sell-out window for this bet has closed — it now rides to settlement. · Muda wa kuuza dau hili umefungwa — litaenda hadi malipo.\"",
    to: "    if (p.houseBotId != null) {\n      return { ok: false as const, error: \"Liquidity stakes can't be sold early.\"",
    expect: "1.12b · …in the exit window's own words, byte for byte, with no house word",
    suite: "money-mem",
  },
  {
    name: "D19-4 · the offer reports a house reason again",
    file: SVC,
    from: "    : housePosition ? \"WINDOW_PASSED\" as const",
    to: "    : housePosition ? \"HOUSE_POSITION\" as unknown as \"WINDOW_PASSED\"",
    expect: "1.11 · cashOutValue offers no sale on a house position, as a closed window (WINDOW_PASSED)",
    suite: "money-mem",
  },
  {
    name: "D19-5 · the holder is told about designation again, under another notification kind",
    file: "src/lib/server/house-bot/designation.ts",
    from: "  await houseAudit(\"house_bot.designated\", officerId, { type: \"HouseBot\", id: written.bot.id }, { botId: written.bot.id, holderUserId: userId });",
    to: "  await houseAudit(\"house_bot.designated\", officerId, { type: \"HouseBot\", id: written.bot.id }, { botId: written.bot.id, holderUserId: userId });\n  await (await import(\"../notification-service\")).notifyWin(userId, 0, { en: \"x\", sw: \"x\", zh: \"x\" }, \"/positions\");",
    expect: "4.1d · D19c · designation tells the holder NOTHING",
    suite: "designation-mem",
  },
  // ── C4 step 11b · A24's EXPLAIN pins (ruling 161) have their own mutation ──────────────────────────────────────
  // A predicate rewritten to mean the same thing stops matching the PARTIAL index (… WHERE "houseBotId" IS NOT NULL),
  // so the read falls back to a sequential scan of Position — invisible to every functional case, and the whole point
  // of the pins. The fixture is 1,000,046 positions, 20,017 of them house-marked. The anchor is a plain string
  // because the line it quotes contains backticks.
  {
    name: "A24-pin · openExposure's marker predicate no longer matches the partial index",
    file: DAL,
    from: "      + ` WHERE \"houseBotId\" IS NOT NULL AND \"status\"::text = 'OPEN' AND ($1::text IS NULL OR \"houseBotId\" = $1::text)`",
    to: "      + ` WHERE coalesce(\"houseBotId\", '') <> '' AND \"status\"::text = 'OPEN' AND ($1::text IS NULL OR \"houseBotId\" = $1::text)`",
    expect: "7.15 · A24 · EXPLAIN at 1M/20k: openExposure, every bot — no sequential scan on Position",
    suite: "money-pg",
  },
];
