-- Restore the eight trigram search indexes that 20260925120000_marketing_consent_suppression dropped.
--
-- WHAT HAPPENED: that migration (marketing U6) was generated with `prisma migrate diff` against a
-- database that still held objects `schema.prisma` does not declare. These GIN indexes are raw SQL
-- that `schema.prisma` cannot express, so the diff read them as drift and emitted
-- `DROP INDEX "…_trgm_idx"` for all eight; production applied it on 2026-09-25. Found 2026-09-25
-- (marketing S6), repaired here (S7, on Ali's delegation of 2026-09-26).
--
-- WHAT THIS DOES: re-creates them with the ORIGINAL statements, copied byte-for-byte from
-- 20260728030000_search_trgm_small_tables (lines 40–62) — ⛔ never regenerated by `migrate diff`,
-- which renders a GIN index as `USING GIN ("titleEn" gin_trgm_ops ASC)`, a form Postgres rejects
-- (`scripts/db-backup.mts`). `IF NOT EXISTS` makes the file a no-op anywhere they already exist.
--
-- SAFETY: the same as the original's — these are the SMALL tables (markets and AI-usage events). A
-- plain CREATE INDEX blocks writes on its table for the build, which at this size is milliseconds;
-- ⛔ no CONCURRENTLY (`migrate deploy` wraps the file in a transaction, and CONCURRENTLY fails
-- 25001 inside one). Expand-only: this file drops nothing.
--
-- ⛔ AND THE NEXT `migrate diff` WILL TRY TO DROP THEM AGAIN, because the schema still cannot see
-- them. `test:migration-ownership` now refuses any migration that drops an object an earlier
-- migration created unless the drop is declared with its owning lane — delete those lines by hand.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- PredictionMarket: the board, admin curation queue and resolver queue all search
-- these five columns (MARKET_SEARCH.default in src/lib/search/fields.ts).
CREATE INDEX IF NOT EXISTS "PredictionMarket_titleEn_trgm_idx"
  ON "PredictionMarket" USING GIN ("titleEn" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "PredictionMarket_titleSw_trgm_idx"
  ON "PredictionMarket" USING GIN ("titleSw" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "PredictionMarket_titleZh_trgm_idx"
  ON "PredictionMarket" USING GIN ("titleZh" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "PredictionMarket_category_trgm_idx"
  ON "PredictionMarket" USING GIN ("category" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "PredictionMarket_resolutionCriterion_trgm_idx"
  ON "PredictionMarket" USING GIN ("resolutionCriterion" gin_trgm_ops);

-- AiUsageEvent: /admin/ai-usage is one of only two searches already in SQL, so
-- this one pays off immediately (AI_USAGE_SEARCH.default).
CREATE INDEX IF NOT EXISTS "AiUsageEvent_model_trgm_idx"
  ON "AiUsageEvent" USING GIN ("model" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "AiUsageEvent_errorType_trgm_idx"
  ON "AiUsageEvent" USING GIN ("errorType" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "AiUsageEvent_detail_trgm_idx"
  ON "AiUsageEvent" USING GIN ("detail" gin_trgm_ops);
