// sell-price-guard: the refused sale's toast passes its words; the toaster draws every amount as `.amount` (round 5, R5-E).
import { readFileSync, writeFileSync } from "node:fs";
const p = "F:/kipindi-r5e/scripts/sell-price-guard.test.mts";
let s = readFileSync(p, "utf8");
const rep = (a, b) => { const n = s.split(a).length - 1; if (n !== 1) throw new Error(`${n} × ${a.slice(0, 80)}`); s = s.replace(a, () => b); };
const NL = "\r\n";
// the source world gains the toaster
rep(`const SHELL_LAZY = "src/components/layout/shell-lazy.tsx";${NL}const SOURCES = [SVC, ACTIONS, BUTTON, CASHOUT_SUITE, POSITIONS, MARKET_PAGE, CARD, VIEW, RESULT, HOST, SHELL, SHELL_LAZY];`,
  `const SHELL_LAZY = "src/components/layout/shell-lazy.tsx";${NL}/** Round 5 (R5-E): the toaster, which draws every amount a toast states as an \`.amount\` — the refused sale's figures among them. */${NL}const TOAST = "src/components/ui/toast.tsx";${NL}const SOURCES = [SVC, ACTIONS, BUTTON, CASHOUT_SUITE, POSITIONS, MARKET_PAGE, CARD, VIEW, RESULT, HOST, SHELL, SHELL_LAZY, TOAST];`);
// the calm toast hands its words as written
rep(`const TOAST_CALM = 'lastRefusalToast = toast({ title: t.toast.couldntCashOut, description: keepFiguresWhole(msg), variant: fault ? "danger" : "factual", durationMs: 0 });';`,
  `const TOAST_CALM = 'lastRefusalToast = toast({ title: t.toast.couldntCashOut, description: msg, variant: fault ? "danger" : "factual", durationMs: 0 });';`);
// the helper pins become the toaster's
rep(`/** The helper a refused sale's toast keeps its figures whole with: each figure one \`.amount\` (\`moneyRuns\`). ⚠️ Pin moved${NL} *  2026-10-09 (round 5, R5-E, review 3 H4's sweep): it joined "TZS" to its number with a no-break space — a character in${NL} *  the toast's text, travelling into a copy and a find-in-page; the toast now takes nodes, and no character is built. */${NL}const NO_BREAK_LINE = 'String.fromCharCode(160)';${NL}const WHOLE = 'export const keepFiguresWhole = (sentence: string) => moneyRuns(sentence);';`,
  `/** How a refused sale's figures stay whole: the toaster draws every amount in a toast's words as one \`.amount\` (\`moneyRuns\`:${NL} *  whole and mono, §M4), title and sentence. ⚠️ Pins moved 2026-10-09 (round 5, R5-E, review 3 H4's sweep): the Sell button${NL} *  passed its sentence through \`keepFiguresWhole\` (sell-result.tsx), which joined "TZS" to its number with a no-break space —${NL} *  a character in the toast's text, travelling into a copy and a find-in-page — and every other toast's figures could split${NL} *  at "TZS" and were not mono. Now one rule, in the toaster, for every toast; no character is built anywhere. */${NL}const NO_BREAK_LINE = 'String.fromCharCode(160)';${NL}const TOAST_IMPORT = 'import { moneyRuns } from "@/lib/fill-nodes";';${NL}const TOAST_TITLE = '<p className="font-display text-[13px] font-semibold text-text leading-tight">{moneyRuns(toast.title)}</p>';${NL}const TOAST_WORDS = '<p className="mt-0.5 text-body-sm text-text-muted leading-snug">{moneyRuns(toast.description)}</p>';`);
// 7.whole
rep(`  ok("7.whole · a refused sale's toast keeps each money figure whole: its sentence goes through keepFiguresWhole, which sets each figure as one \`.amount\` (moneyRuns: whole and mono, §M4) and inserts no character (S6 A8f's promise for the moved price's sentence, which only the toast draws since A8h)",${NL}    TOAST_CALM.includes("description: keepFiguresWhole(msg)") && count(refusal, "keepFiguresWhole(msg)") === 1 && count(result, NO_BREAK_LINE) === 0 && count(result, WHOLE) === 1${NL}      && count(result, 'import { moneyRuns } from "@/lib/fill-nodes";') === 1,${NL}    show({ helper: count(result, WHOLE), space: count(result, NO_BREAK_LINE) }));`,
  `  const toastSrc = text(W, TOAST);${NL}  ok("7.whole · a refused sale's toast keeps each money figure whole: it hands the toast its sentence as written, and the toast draws every amount in its words as one \`.amount\` (moneyRuns: whole and mono, §M4) — no character inserted, here, in the result's module or in the toast (S6 A8f's promise for the moved price's sentence, which only the toast draws since A8h)",${NL}    TOAST_CALM.includes("description: msg,") && count(refusal, "description: msg,") === 1 && count(toastSrc, TOAST_IMPORT) === 1 && count(toastSrc, TOAST_TITLE) === 1 && count(toastSrc, TOAST_WORDS) === 1${NL}      && [button, result, toastSrc].every((x) => count(x, NO_BREAK_LINE) === 0) && count(result, "keepFiguresWhole") === 0 && count(button, "keepFiguresWhole") === 0,${NL}    show({ words: count(toastSrc, TOAST_WORDS), title: count(toastSrc, TOAST_TITLE), space: [button, result, toastSrc].map((x) => count(x, NO_BREAK_LINE)) }));`);
// plants
rep(`const movedAlarmed = swap(BUTTON, TOAST_CALM, 'lastRefusalToast = toast({ title: t.toast.couldntCashOut, description: keepFiguresWhole(msg), variant: "danger", durationMs: 0 });');`,
  `const movedAlarmed = swap(BUTTON, TOAST_CALM, 'lastRefusalToast = toast({ title: t.toast.couldntCashOut, description: msg, variant: "danger", durationMs: 0 });');`);
rep(`const figureSplits = swap(RESULT, WHOLE, 'export const keepFiguresWhole = (sentence: string) => sentence;');${NL}const toastRawFigure = swap(BUTTON, "description: keepFiguresWhole(msg)", "description: msg");`,
  `const figureSplits = swap(TOAST, TOAST_WORDS, TOAST_WORDS.replace("{moneyRuns(toast.description)}", "{toast.description}"));${NL}const toastNoBreak = swap(BUTTON, "description: msg,", 'description: msg.split("TZS ").join("TZS" + String.fromCharCode(160)),');`);
rep(`  { name: "the toast's figures can split again (the helper hands the sentence back as it was)", expect: ["7.whole"], world: figureSplits, landed: changed(figureSplits, RESULT) },${NL}  { name: "the toast draws the raw sentence ('TZS' can end a line without its number)", expect: ["7.whole"], world: toastRawFigure, landed: changed(toastRawFigure, BUTTON) },`,
  `  { name: "the toast draws its sentence raw again ('TZS' can end a line without its number, and the figure is not mono)", expect: ["7.whole"], world: figureSplits, landed: changed(figureSplits, TOAST) },${NL}  { name: "the refused sale's sentence is joined with a no-break space again (a character in the toast's text, copied and searched)", expect: ["7.whole"], world: toastNoBreak, landed: changed(toastNoBreak, BUTTON) },`);
writeFileSync(p, s, "utf8");
console.log("ok");
