const fs = require("fs");
const p = "F:/kipindi-a8i2/docs/VODACOM-PLAN.md";
let s = fs.readFileSync(p, "utf8");
const re = /Four helpers are fixing the rest of round 3[^\n]*?Every tile is read and measured before anything goes live\./;
if (!re.test(s)) throw new Error("anchor not found");
const next = "**Round 3's findings are fixed on the branch** (R3-A the home hero, ticker and featured card; R3-B the Needle's rest; R3-C lists, empty states and sheets; R3-D the bell, money faces, the market and ticket pages — each with its guards and planted defects). **Turns M6–M8 proved them:** typecheck 0; `test:all` 466/476, each failure main's own or one the branch then fixed (`house-bot-reports`' pins re-measured with a proof, `icon-sizes`, `decomment` — green in M8), except `test:house-bot-disclosure`'s D19a pin, red by construction until the legal tree is main; the header fit 6/6 (least slack 10.7px) and its red; the landmark seal 276 cells, 0 problems; the preview drive 33/33. M7 found three more, fixed: local `qa:live` read \"·</span>Imetolewa\" (a dot sequence fused its words; `DotSeq` now spaces them), needle-rest's §1 a 6.5px jump between frames (the glide now steps the engine whole, `90cb52ea`), and bar geometry measured nothing (it ignores the address it is given; M11 passes it). **Round 4's read (eight readers, every tile measured) verified most of round 3 and found 20 more.** Committed: R4-A (the featured card's Swahili top row, its no-bets pair centred, its pool labelled as money, the ticker's fade clear of its label), R4-B (the Needle treats the chat bubble as an obstacle, shown or faded, ring included), the journey bell's badge clear of the dome. Three helpers fix the rest (the filter bars and notifications; Up & Down, `/live` and the market page; the hub, profile, sheets and page edges). **The classic parity compare (M8) reads 38/39:** both differences are this pass's own — the footer's proposals link balance (classic chrome, so it becomes journey-only) and the classic `/positions` empty state (a page body, so it is named) — a helper reconciles them, then it runs again. Queued under the lock on `90cb52ea`: M9 the 532 edge tiles (running), M10 the journey seal again (M7's server was stopped from outside mid-run), M11 bar geometry, M12 local `qa:live`, M13 needle-rest twice. Then one turn on the final tip proves everything again and round 5's tiles are read; it goes live only when a read finds nothing. **S9's two fixes from ALI-BLADE15 (above) are read here:** `vodacom-visual` rebases onto them before it goes live (both touch the deposit page), and their note on the return receipt's widowed id is taken into the pass.";
s = s.replace(re, () => next);
fs.writeFileSync(p, s);
console.log("ok");
